POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "ewen@mail.com",
    "password":"C1Mot2Passe!",
    "surname":"Ewen",
    "lastname":"Rondin"
}

### PUT

PUT http://localhost:3000/auth/c7a868fb-596c-46c3-ad89-7c06837023b0
Content-Type: application/json

{
    "role":"ADMIN"
}

### GET BOOKS

GET http://localhost:3000/library/

### GET BY ID
GET http://localhost:3000/auth/07290217-31cc-451d-a4c5-cd5e09f103aa

### DELETE BY ID

DELETE http://localhost:3000/auth/07290217-31cc-451d-a4c5-cd5e09f103aa

### CREATE BOOK

POST http://localhost:3000/library/new
Content-Type: application/json

{
    "ISBN":"123054612",
    "title":"Blood Song",
    "author":"Anthony Ryan",
    "editor":"NotKnown",
    "publication_year":2014,
    "total_amount":2
}


### UPDATE BOOK
PUT http://localhost:3000/library/b091262f-59e4-42b1-b247-ea3c4750bb4b
Content-Type: application/json

{
    "editor":"Ace Books",
    "publication_year":2012
}

### BORROW

POST http://localhost:3000/borrow
Content-Type: application/json

{
    "book": "b091262f-59e4-42b1-b247-ea3c4750bb4b"
}