// Connexion Administrateur
// "email": "administrateur@mail.com",
// "password":"Mot2Passe!",
//
// Connexion Libraire
// "email": "librarian@mail.com"
// "password":"Mot2Passe!"
//
// Connexion Normale
// "email": "test@mail.com"
// "password":"Mot2Passe!"

//---------------------------------------------------
// UTILISATEUR
//---------------------------------------------------

### CREATION DE COMPTE
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "",
    "password":"",
    "surname":"",
    "lastname":""
}

### CONNEXION
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "administrateur@mail.com",
    "password":"Mot2Passe!"
}

### INFORMATIONS PERSONELLES
GET http://localhost:3000/auth/me

### MODIFICATION COMPTE ( Admin )
PUT http://localhost:3000/auth/9e3258f8-8f99-47f1-91e7-9dd1b002ecd5
Content-Type: application/json
{
    "role":"STUDENT",
    "whiteliststatus":true
}


//---------------------------------------------------
// GESTION LIVRE
//---------------------------------------------------


### GET BOOKS
GET http://localhost:3000/library


### GET BY ID
GET http://localhost:3000/library/b091262f-59e4-42b1-b247-ea3c4750bb4b


### DELETE BY ID (Libraire)
DELETE http://localhost:3000/library/b091262f-59e4-42b1-b247-ea3c4750bb4b


### CREATE BOOK (Libraire)
POST http://localhost:3000/library/new
Content-Type: application/json

{
    "ISBN":"123054612",
    "title":"Blood Song",
    "author":"Anthony Ryan",
    "editor":"NotKnown",
    "publication_year":2014,
    "total_amount":2
}


### UPDATE BOOK (Libraire)
PUT http://localhost:3000/library/b091262f-59e4-42b1-b247-ea3c4750bb4b
Content-Type: application/json

{
    "editor":"Ace Books",
    "publication_year":2012
}


//---------------------------------------------------
// GESTION EMPRUNTS ( Utilisateurs connectés )
//---------------------------------------------------


### BORROW
POST http://localhost:3000/borrow
Content-Type: application/json

{
    "book": "b091262f-59e4-42b1-b247-ea3c4750bb4b"
}


### LIST BORROW (Libraire)
GET http://localhost:3000/borrow

### INFORMATIONS BORROW (Libraire)
GET http://localhost:3000/borrow/f032b3a5-5263-4b0a-9abe-2f2f553428b8


### UPDATE BORROW (Libraire)
PUT http://localhost:3000/borrow/f032b3a5-5263-4b0a-9abe-2f2f553428b8
Content-Type: application/json

{
    "book": "b091262f-59e4-42b1-b247-ea3c4750bb4b"
}

### DELETE BORROW (Libraire)
DELETE http://localhost:3000/borrow/f032b3a5-5263-4b0a-9abe-2f2f553428b8